Try to work around a bug with PyCParser
Causing

  AssertionError: sorry, but this version only supports 100 named groups

There is a bug with PyCParser - See
https://github.com/pyca/cryptography/issues/3187